apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: services.aws.platformref.crossplane.io
spec:
  group: aws.platformref.crossplane.io
  names:
    kind: Services
    plural: services
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              operators:
                type: object
                description: Configuration for operators.
                properties:
                  prometheus:
                    type: object
                    description: Configuration for the Prometheus operator.
                    properties:
                      version:
                        type: string
                        description: Prometheus operator version to run.
                  flux2:
                    type: object
                    description: Configuration for the Flux2 operators.
                    properties:
                      version:
                        type: string
                        description: flux2 operators version to run.
                  flux2-sync:
                    type: object
                    description: Configuration for the Flux2-Sync helm-chart
                    properties:
                      version:
                        type: string
                        description: flux2-sync helm-chart version to run.
                      url:
                        type: string
                        description: The repository URL (HTTPS)
                      branch:
                        type: string
                        description: The Git reference to checkout and monitor for changes
              providerConfigRef:
                type: object
                description: "A reference to the ProviderConfig of the cluster that services should
                be deployed to."
                properties:
                  name:
                    type: string
                    description: "Name of the Kubernetes provider configuration.
                      This will typically be the name of the cluster with a
                      five character suffix appended."
                required:
                - name
            required:
            - providerConfigRef
