apiVersion: aws.platformref.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-aws-cluster
spec:
  id: platform-ref-aws-cluster
  parameters:
    nodes:
      count: 3
      size: small
    services:
      operators:
        prometheus:
          version: "25.1.0"
        flux2:
          version: "0.8.5"
        flux2-sync:
          version: "0.3.6"
          url: https://github.com/upbound/platform-ref-aws.git
          branch: main
    networkRef:
      id: platform-ref-aws-network
  writeConnectionSecretToRef:
    name: platform-ref-aws-cluster
