apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 10m0s
  timeout: 8m
  chart:
    spec:
      chart: crossplane
      version: v1.5
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: crossplane-system
