apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xclusters.aws.platformref.upbound.io
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: aws.platformref.upbound.io/v1alpha1
    kind: XCluster
  resources:
    - name: XNetwork
      base:
        apiVersion: aws.platform.upbound.io/v1alpha1
        kind: XNetwork
      patches:
        - fromFieldPath: spec.parameters.id
          toFieldPath: spec.parameters.id
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.parameters.region
        - fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.parameters.deletionPolicy
        - fromFieldPath: spec.parameters.providerConfigName
          toFieldPath: spec.parameters.providerConfigName
        - fromFieldPath: spec.parameters.networkSelector
          toFieldPath: spec.compositionSelector.matchLabels[type]
        - type: ToCompositeFieldPath
          fromFieldPath: status.subnetIds
          toFieldPath: status.subnetIds
          policy:
            fromFieldPath: Required

    - name: XEKS
      base:
        apiVersion: aws.platform.upbound.io/v1alpha1
        kind: XEKS
      connectionDetails:
        - fromConnectionSecretKey: kubeconfig
      patches:
        - fromFieldPath: spec.parameters.id
          toFieldPath: metadata.labels[xeks.aws.platform.upbound.io/cluster-id]
        - fromFieldPath: spec.parameters.id
          toFieldPath: spec.parameters.id
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.parameters.region
        - fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.parameters.deletionPolicy
        - fromFieldPath: spec.parameters.providerConfigName
          toFieldPath: spec.parameters.providerConfigName
        - fromFieldPath: spec.parameters.id
          toFieldPath: metadata.annotations[crossplane.io/external-name]
        - fromFieldPath: metadata.uid
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-eks"
        - fromFieldPath: spec.writeConnectionSecretToRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - fromFieldPath: spec.parameters.version
          toFieldPath: spec.parameters.version
        - fromFieldPath: spec.parameters.nodes.count
          toFieldPath: spec.parameters.nodes.count
        - fromFieldPath: spec.parameters.nodes.instanceType
          toFieldPath: spec.parameters.nodes.instanceType
        - fromFieldPath: spec.parameters.iam.roleArn
          toFieldPath: spec.parameters.iam.roleArn
        - fromFieldPath: spec.parameters.iam.userArn
          toFieldPath: spec.parameters.iam.userArn

    - name: XOss
      base:
        apiVersion: observe.platform.upbound.io/v1alpha1
        kind: XOss
      patches:
        - fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.parameters.deletionPolicy
        - fromFieldPath: spec.parameters.id
          toFieldPath: spec.parameters.id
        - fromFieldPath: spec.parameters.operators.prometheus.version
          toFieldPath: spec.parameters.operators.prometheus.version

    - name: XFlux
      base:
        apiVersion: gitops.platform.upbound.io/v1alpha1
        kind: XFlux
      patches:
        - fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.parameters.deletionPolicy
        - fromFieldPath: spec.parameters.id
          toFieldPath: spec.parameters.providerConfigName
        - fromFieldPath: spec.parameters.operators.flux.version
          toFieldPath: spec.parameters.operators.flux.version
        - fromFieldPath: spec.parameters.operators.flux-sync.version
          toFieldPath: spec.parameters.operators.flux-sync.version
        - fromFieldPath: spec.parameters.gitops
          toFieldPath: spec.parameters.source

    - name: usageXEksByXFlux
      base:
        apiVersion: apiextensions.crossplane.io/v1alpha1
        kind: Usage
        spec:
          of:
            apiVersion: aws.platform.upbound.io/v1alpha1
            kind: XEKS
            resourceSelector:
              matchControllerRef: true
          by:
            apiVersion: gitops.platform.upbound.io/v1alpha1
            kind: XFlux
            resourceSelector:
              matchControllerRef: true

    - name: usageXEksByXOss
      base:
        apiVersion: apiextensions.crossplane.io/v1alpha1
        kind: Usage
        spec:
          of:
            apiVersion: aws.platform.upbound.io/v1alpha1
            kind: XEKS
            resourceSelector:
              matchControllerRef: true
          by:
            apiVersion: observe.platform.upbound.io/v1alpha1
            kind: XOss
            resourceSelector:
              matchControllerRef: true

    - name: usageXEksByArbitraryLabeledRelease
      base:
        apiVersion: apiextensions.crossplane.io/v1alpha1
        kind: Usage
        spec:
          of:
            apiVersion: aws.platform.upbound.io/v1alpha1
            kind: XEKS
            resourceSelector:
              matchControllerRef: true
          by:
            apiVersion: helm.crossplane.io/v1beta1
            kind: Release
            resourceSelector:
              matchLabels:
                platform.upbound.io/deletion-ordering: enabled
      readinessChecks:
        - type: None
